---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  labels:
    app: k8s-talk-clusterconnect
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  k8s-talk-clusterconnect
  namespace: k8s-talk-clusterconnect
  labels:
    app: k8s-talk-clusterconnect
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-talk-clusterconnect
  labels:
    app: k8s-talk-clusterconnect
subjects:
- kind: ServiceAccount
  name: k8s-talk-clusterconnect
  namespace: k8s-talk-clusterconnect
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io