apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-talk-cluster-connect
spec:
  selector:
    matchLabels:
      app: k8s-talk-cluster-connect
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-talk-cluster-connect
    spec:
      containers:
      - name: k8s-talk-cluster-connect
        image: simontheleg/k8s-talk-cluster-connect:v0.2.0
        resources:
          limits:
            memory: "20Mi"
            cpu: "15m"